name: metaphor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  build:
    name: Build Go Application
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./..
